[versions]
kotlin = "2.0.21"
compose = "1.6.11"
coroutines = "1.9.0"
ktor = "3.0.0"
slf4j = "2.0.16"
androidGradlePlugin = "8.5.2"
hotswapAgent = "2.0.1"
junit = "5.10.1"
javassist = "3.30.2-GA"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientDarwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
hotswapAgentCore = { module = "org.hotswapagent:hotswap-agent-core", version.ref = "hotswapAgent" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }