[versions]
kotlin = "2.2.21"
compose = "1.9.0"
composeMin = { prefer = "1.8.2" }
coroutines = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxBenchmark = "0.4.14"
kotlinxBinaryCompatibilityValidator = "0.18.1"
kotlinxSerialization = "1.9.0"
kotlinxLincheck = "3.3.2"
androidGradlePlugin = "8.11.1"
junit = "5.14.1"
javassist = "3.30.2-GA"
asm = "9.9"
evas = "1.3.0"
ktor = "3.3.2"
shadow = "9.2.2"
kaml = "0.103.0"
skiko = "0.9.27"
gradlePluginPublish = "2.0.0"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

benchmark-runtime = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinxBenchmark" }
benchmark-gradlePlugin = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-plugin", version.ref = "kotlinxBenchmark" }

binaryCompatibilityValidator-gradlePlugin = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinxBinaryCompatibilityValidator" }

kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxSerialization-kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }

lincheck = { module = "org.jetbrains.lincheck:lincheck", version.ref = "kotlinxLincheck" }

evas = { module = "io.sellmair:evas", version.ref = "evas" }
evas-compose = { module = "io.sellmair:evas-compose", version.ref = "evas" }

compose-gradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose" }
compose-compiler-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version = "1.7.3" }

compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMin" }
compose-desktop-common = { module = "org.jetbrains.compose.desktop:desktop", version.ref = "composeMin" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMin" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMin" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMin" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }

shadow-gradlePlugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
pluginPublish-gradlePlugin = { module = "com.gradle.plugin-publish:com.gradle.plugin-publish.gradle.plugin", version.ref = "gradlePluginPublish" }

skiko-awt = { module = "org.jetbrains.skiko:skiko-awt", version.ref = "skiko" }
